.TH "ipv6logconv" "8" "2.0.0" "Peter Bieringer <pb@bieringer.de>" "system tools"
.SH "NAME"
ipv6logconv \- HTTP server log file converter for statistics
.SH "SYNOPSIS"
cat /var/log/httpd/access_log | \fBipv6logconv\fR [\fIOPTIONS\fR]
.SH "DESCRIPTION"
This program converts IPv4/IPv6 addresses in HTTP server log files

The converted output can be used to create statistics with analog

Takes data from stdin, proceed it to stdout
.SH "OPTIONS"
.LP 
General options:
.TP 
\fB[\-d|\-\-debug \fIDEBUGVALUE\fR\fB]\fR
debug value (bitwise like) can also be set by IPV6CALC_DEBUG environment value
.TP 
\fB[\-v|\-\-version [\-v [\-v]]]\fR
version information (2 optional detail levels)
.TP 
\fB[\-v|\-\-version \-h]\fR
explanation of feature tokens
.TP 
\fB[\-V|\-\-verbose]\fR
be more verbose
.TP 
\fB[\-h|\-\-help|\-?]\fR
this online help
.LP 
Performance options:
.TP 
\fB[\-n|\-\-nocache]\fR
disable caching
.TP 
\fB[\-c|\-\-cachelimit \fIVALUE\fR\fB]\fR
set cache limit; default: \fB20\fR, maximum: \fB200\fR.
.LP 
Output options:
.TP 
\fB[\-\-out \fIOUTPUTTYPE\fR\fB]\fR
Specify output type:
.RS
.TP 
\fBaddrtype\fR
Address type
.TP 
\fBouitype\fR
OUI (IEEE) type
.TP 
\fBipv6addrtype\fR
IPv6 address type
.TP 
\fBany\fR
any type
.RE
.SH "SEE ALSO"
ipv6calc(8)
.SH "REPORTING BUGS"
Report bugs via GitHub:
.UR https://github.com/pbiering/ipv6calc/issues
 https://github.com/pbiering/ipv6calc/issues
.UE
.PP 
Homepage:
.UR http://www.deepspace6.net/projects/ipv6calc.html
http://www.deepspace6.net/projects/ipv6calc.html
.UE
.SH "LICENSE"
GPLv2
.SH "AUTHORS"
Peter Bieringer <pb@bieringer.de>

