.TH "ipv6loganon" "8" "2007-02-01" "Niko Tyni <ntyni@iki.fi>" ""
.SH "NAME"
ipv6loganon \- HTTP server log file anonymizer
.SH "SYNOPSIS"
.PP
.B ipv6loganon 
[
.B \-d
.I value
] [
.B \-V
] [
.B \-n
] [
.B \-c 
.I value
] [
.B \-\-mask\-ipv4
.I bits
] [
.B \-\-no\-mask\-iid
] [
.B \-\-anonymize\-standard
]
.SH "DESCRIPTION"
.PP
.B ipv6loganon
is a HTTP server log file anonymizer
.PP
It expects a log line on stdin with an IPv4/IPv6 address as first token.
.PP
This token would be anonymized according to given/default options.
.PP
The anonymizer would keep as much information as possible for IPv6 address types.
.PP
Client-side IID would be anonymized by
.IP
\(bu EUI-48 based: serial number would be zero'ed, keeping OID

\(bu EUI-64 based: serial number would be zero'ed, keeping OID

\(bu ISATAP: client IPv4 address would be anonymized by given IPv4 mask

\(bu TEREDO: client IPv4 address would be anonymized by given IPv4 mask,
client port would be zero'ed

\(bu 6to4(Microsoft): client IPv4 address would be anonymized by given IPv4 mask

\(bu local: whole IID would be zero'ed
.PP
Client-side SLA would be anonymized by 
.IP
\(bu SLA would be zero'ed
.PP
Prefix would be anonymized by
.IP
\(bu 6to4: client IPv4 address would be anonymized by given IPv4 mask
.PP
Compat/Mapped IPv4 addresses would be anonymized by
.IP
\(bu IPv4 address would be anonymized by given IPv4 mask
.PP
Afterwards, the modified address and the trailing line would be printed to stdout.
.SH "OPTIONS"
.SS "GENERAL"
.TP
.B \-d, \-\-debug <debug value>
debug value (bitwise like)
.TP
.B \-V, \-\-verbose
be verbose
.TP
.B \-n, \-\-nocache
disable caching
.TP
.B \-c, \-\-cachelimit
set cache limit (default: 20, maximum: 200)
.SS "OUTPUT ANONYMIZATION"
.TP
.B \-\-mask\-ipv4 <bits>
mask all IPv4 addresses [0-32], default 8 even if occurs in IPv6-IID
.TP
.B \-\-no\-mask\-iid
do not mask non-IPv4 based IPv6-IID
.TP
.B \-\-anonymize\-standard
preset for standard anonymization
.PP
Default settings:
.B mask-ipv4=8 mask-iid

.SH "EXAMPLE"
Original lines (stdin):
.PP
207.46.98.53 - - [01/Jan/2007:00:01:15 +0100] "GET /Linux+IPv6-HOWTO/x1112.html HTTP/1.0" 200 6162 "-" "msnbot/1.0 (+http://search.msn.com/msnbot.htm)" 253 6334

2002:52b6:6b01:1:216:17ff:fe01:2345 - - [10/Jan/2007:15:04:28 +0100] "GET /favicon.ico HTTP/1.1" 200 4710 "http://www.bieringer.de/linux/IPv6/" "Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.8.0.9) Gecko/20061219 Fedora/1.5.0.9-1.fc6 Firefox/1.5.0.9 pango-text" 413 5005
.PP
Modified lines (stdout):
.PP
207.46.98.0 - - [01/Jan/2007:00:01:15 +0100] "GET /Linux+IPv6-HOWTO/x1112.html HTTP/1.0" 200 6162 "-" "msnbot/1.0 (+http://search.msn.com/msnbot.htm)" 253 6334

2002:52b6:6b00:0:216:17ff:fe00:0 - - [10/Jan/2007:15:04:28 +0100] "GET /favicon.ico HTTP/1.1" 200 4710 "http://www.bieringer.de/linux/IPv6/" "Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.8.0.9) Gecko/20061219 Fedora/1.5.0.9-1.fc6 Firefox/1.5.0.9 pango-text" 413 5005

.SH "AUTHORS"
.PP 
Peter Bieringer <pb@bieringer.de>
.SH "SEE ALSO"
.B ipv6calc(8)
