.TH "ipv6logconv" "8" "0.0.1" "Matanuki@Goudge.org" ""
.SH "NAME"
.LP
ipv6logconv \- a small IPv6 log converter written in C.
.LP
.SH "SYNTAX"
.nf
.fam C
 General:
  [\-d|\-\-debug <debug value>] : debug value (bitwise like)
  [\-q|\-\-quiet] : be more quiet
 Output:
  [\-\-out <output type>] : specify output type
  Available output types:  \-\-out \-?
.SH "AUTHORS"
.LP 
Peter Bieringer <pb@bieringer.de>

