.TH "ipv6calc" "8" "0.97.4" "Peter Bieringer <pb@bieringer.de>" "system administration"
.SH "NAME"
ipv6calc
.SH "SYNOPSIS"
ipv6calc [\fIOPTIONS\fP] \fB<input data>\fR

or in pipe mode

echo \fB<input data>\fR | ipv6calc [\fIOPTIONS\fP]
.SH "DESCRIPTION"
.LP 
This program formats and calculates IPv6/IPv4/MAC addresses and can do many more tricky things.
.SH "OPTIONS"
.LP 
General options:
.TP 
\fB[\-d|\-\-debug \fIDEBUGVALUE\fR\fB]\fR : debug value (bitwise like) can also be set by IPV6CALC_DEBUG environment value
.TP 
\fB[\-v|\-\-version [\-v [\-v]]]\fR   : version information (2 optional detail levels)
.TP 
\fB[\-v|\-\-version \-h]\fR          : explanation of feature tokens
<TP
\fB[\-V|\-\-verbose]\fR             : be more verbose
.TP 
\fB[\-h|\-\-help|\-?]\fR             : this online help
.LP 
External database options (depending on compiled\-in suppport):
.TP 
\fB[\-\-db\-ip2location\-disable      ]\fR : IP2Location support disabled
.TP 
\fB[\-\-db\-ip2location\-dir\fR \fIDIRECTORY\fR\fB]\fR : IP2Location database directory (default: /usr/share/IP2Location)
.TP 
\fB[\-\-db\-geoip\-disable            ]\fR : GeoIP support disabled
.TP 
\fB[\-\-db\-geoip\-dir\fR       \fIDIRECTORY\fR\fB]\fR : GeoIP database directory (default: /usr/share/GeoIP)
.LP 
Special options:
.TP 
\fB[\-q|\-\-quiet]\fR               : be more quiet (auto\-enabled in pipe mode)
.TP 
\fB[\-f|\-\-flush]\fR               : flush each line in pipe mode
.LP 
Usage with new style options:
.TP 
\fB[\-\-in|\-I\fR \fIINPUT\-TYPE\fR\fB]\fR   : specify input  type (default: autodetect)
.TP 
\fB[\-\-out|\-O\fR \fIOUTPUT\-TYPE\fR\fB]\fR : specify output type (sometimes: autodetect)
.TP 
\fB[\-\-action|\-A\fR \fIACTION\fR\fB]\fR   : specify action (default: format conversion, sometimes: autodetect)
.TP 
\fB[<format option> ...]\fR : specify format options
.TP 
\fB<input data> [...]\fR    : input data
.TP 
  Available input  types:  \fB[\-m] \-I|\-\-in     \-?|\-h|\-\-help\fR
.TP 
  Available output types:  \fB[\-m] \-O|\-\-out    \-?|\-h|\-\-help\fR
.TP 
  Available action types:  \fB[\-m] \-A|\-\-action \-?|\-h|\-\-help\fR
.LP 
 Other usage:
.TP 
\fB\-\-showinfo|\-i [\-\-machine_readable|\-m]\fR : show information about input data
.TP 
\fB\-\-showinfo|\-i \-\-show_types\fR            : show available types on '\-m'
.LP 
Usage with shortcut options: <shortcut option> [<format option> ...] <input data>
.br 
for more information and available format options use: <shortcut option> \-?|\-h|\-\-help
.TP 
\fB\-r|\-\-addr2ip6_int\fR (\-O revnibbles.int)
.TP 
\fB\-r|\-\-addr_to_ip6int\fR (\-O revnibbles.int)
.TP 
\fB\-a|\-\-addr2ip6_arpa\fR (\-O revnibbles.arpa)
.TP 
\fB\-a|\-\-addr_to_ip6arpa\fR (\-O revnibbles.arpa)
.TP 
\fB\-b|\-\-addr_to_bitstring\fR (\-O bitstring)
.TP 
\fB   \-\-addr2compaddr\fR (\-\-printcompressed)
.TP 
\fB   \-\-addr_to_compressed\fR (\-\-printcompressed)
.TP 
\fB   \-\-addr2uncompaddr\fR (\-\-printuncompressed)
.TP 
\fB   \-\-addr_to_uncompressed\fR (\-\-printuncompressed)
.TP 
\fB   \-\-addr_to_base85\fR (\-I ipv6addr \-O base85)
.TP 
\fB   \-\-base85_to_addr\fR (\-I base85 \-O ipv6addr)
.TP 
\fB   \-\-mac_to_eui64\fR (\-I mac \-O eui64)
.TP 
\fB   \-\-addr2fulluncompaddr\fR (\-\-printfulluncompressed)
.TP 
\fB   \-\-addr_to_fulluncompressed\fR (\-\-printfulluncompressed)
.TP 
\fB   \-\-addr2if_inet6\fR (\-I ipv6addr \-O ifinet6)
.TP 
\fB   \-\-addr_to_ifinet6\fR (\-I ipv6addr \-O ifinet6)
.TP 
\fB   \-\-if_inet62addr\fR (\-I ifinet6 \-O ipv6addr \-\-printcompressed)
.TP 
\fB   \-\-ifinet6_to_compressed\fR (\-I ifinet6 \-O ipv6addr \-\-printcompressed)
.TP 
\fB   \-\-eui64_to_privacy\fR (\-I iid_token \-O iid_token \-A genprivacyiid)
.TP 
\fB   \-\-ipv4_to_6to4addr\fR (\-I ipv4 \-O ipv6addr \-A conv6to4)
.SH "REPORTING BUGS"
Report bugs to <ipv6calc@lists.deepspace6.net> or to the authors.
.br 
Homepage: http://www.deepspace6.net/projects/ipv6calc.html
.SH "EXAMPLES"
To run this program the standard way type:
.LP 
ipv6calc \-\-showinfo \-i \-m ::1
.TP 
ipv6calc \-\-showinfo \-m 127.0.0.1
.TP 
ipv6calc \-\-showinfo \-\-show_types
.TP 
ipv6calc \-\-ipv4_to_6to4addr 127.0.0.1
.TP 
ipv6calc \-\-addr_to_uncompressed ::1
.SH "COPYRIGHT"
GPLv2
.SH "AUTHORS"
Peter Bieringer <pb@bieringer.de>
